// homepage/homepage/content/docs/code-snippets/key-features/authentication/passphrase/AuthModal.svelte
<script lang="ts">
  import { usePassphraseAuth } from "jazz-tools/svelte";
  import { wordlist } from "./wordlist";
  let loginPassphrase = $state('');
  const auth = usePassphraseAuth({
    // Must be inside the JazzProvider!
    wordlist: wordlist,
  });
  const handleSignUp = async () => {
    await auth.signUp();
  };

  const handleLogIn = async () => {
    await auth.logIn(loginPassphrase);
  };
</script>

{#if auth.state === "signedIn"}
  <div>You are already signed in</div>
{:else}
<div>
  <label>
    Your current passphrase
    <textarea readOnly value={auth.passphrase} rows={5}></textarea>
  </label>
  <button onclick={handleSignUp}>I have stored my passphrase</button>
  <label>
    Log in with your passphrase
    <textarea
      bind:value={loginPassphrase}
      placeholder="Enter your passphrase"
      rows={5}
      required
    ></textarea>
  </label>
  <button onclick={handleLogIn}>Log in</button>
</div>
{/if}

// homepage/homepage/content/docs/code-snippets/key-features/authentication/passphrase/AuthModal.tsx
import { useState } from "react";
import { usePassphraseAuth } from "jazz-tools/react";
type AuthModalProps = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
};
// #region Basic
import { wordlist } from "./wordlist";

export function AuthModal({ open, onOpenChange }: AuthModalProps) {
  const [loginPassphrase, setLoginPassphrase] = useState("");

  const auth = usePassphraseAuth({
    // Must be inside the JazzProvider!
    wordlist: wordlist,
  });

  if (auth.state === "signedIn") {
    // You can also use `useIsAuthenticated()`
    return <div>You are already signed in</div>;
  }

  const handleSignUp = async () => {
    await auth.signUp();
    onOpenChange(false);
  };

  const handleLogIn = async () => {
    await auth.logIn(loginPassphrase);
    onOpenChange(false);
  };

  return (
    <div>
      <label>
        Your current passphrase
        <textarea readOnly value={auth.passphrase} rows={5} />
      </label>
      <button onClick={handleSignUp}>I have stored my passphrase</button>
      <label>
        Log in with your passphrase
        <textarea
          value={loginPassphrase}
          onChange={(e) => setLoginPassphrase(e.target.value)}
          placeholder="Enter your passphrase"
          rows={5}
          required
        />
      </label>
      <button onClick={handleLogIn}>Log in</button>
    </div>
  );
}
// #endregion
