// packages/jazz-tools/src/svelte/Provider.svelte
<script
  lang="ts"
  generics="S extends (AccountClass<Account> & CoValueFromRaw<Account>) | AnyAccountSchema"
>
  import type { AuthSecretStorage, InstanceOfSchema } from "jazz-tools";
  import {
    Account,
    type AccountClass,
    type AnyAccountSchema,
    type CoValueFromRaw,
  } from "jazz-tools";
  import {
    JazzBrowserContextManager,
    type JazzContextManagerProps,
  } from "jazz-tools/browser";
  import { type Snippet, setContext, untrack } from "svelte";
  import { JAZZ_AUTH_CTX, JAZZ_CTX, type JazzContext } from "./jazz.svelte.js";

  let props: JazzContextManagerProps<S> & {
    children?: Snippet;
    authSecretStorageKey?: string;
  } = $props();

  const contextManager = new JazzBrowserContextManager<S>({
    authSecretStorageKey: props.authSecretStorageKey,
  });

  const ctx = $state<JazzContext<InstanceOfSchema<S>>>({ current: undefined });

  setContext<JazzContext<InstanceOfSchema<S>>>(JAZZ_CTX, ctx);
  setContext<AuthSecretStorage>(
    JAZZ_AUTH_CTX,
    contextManager.getAuthSecretStorage(),
  );

  $effect(() => {
    props.sync.when;
    props.sync.peer;
    props.storage;
    props.guestMode;
    return untrack(() => {
      if (!props.sync) return;

      contextManager
        .createContext({
          sync: props.sync,
          storage: props.storage,
          guestMode: props.guestMode,
          AccountSchema: props.AccountSchema,
          defaultProfileName: props.defaultProfileName,
          onAnonymousAccountDiscarded: props.onAnonymousAccountDiscarded,
          onLogOut: props.onLogOut,
        })
        .catch((error) => {
          console.error("Error creating Jazz browser context:", error);
        });
    });
  });

  $effect(() => {
    return contextManager.subscribe(() => {
      ctx.current = contextManager.getCurrentValue();
    });
  });
</script>

{#if ctx.current}
  {@render props.children?.()}
{/if}

// packages/jazz-tools/src/react-native-core/provider.tsx
import {
  Account,
  AccountClass,
  AnyAccountSchema,
  CoValueFromRaw,
  InstanceOfSchema,
  JazzContextType,
  KvStore,
} from "jazz-tools";
import { JazzContext, JazzContextManagerContext } from "jazz-tools/react-core";
import React, { useEffect, useRef } from "react";
import type { JazzContextManagerProps } from "./ReactNativeContextManager.js";
import { ReactNativeContextManager } from "./ReactNativeContextManager.js";
import { setupKvStore } from "./platform.js";

export type JazzProviderProps<
  S extends
    | (AccountClass<Account> & CoValueFromRaw<Account>)
    | AnyAccountSchema,
> = {
  children: React.ReactNode;
  kvStore?: KvStore;
  authSecretStorageKey?: string;
} & JazzContextManagerProps<S>;

/** @category Context & Hooks */
export function JazzProviderCore<
  S extends
    | (AccountClass<Account> & CoValueFromRaw<Account>)
    | AnyAccountSchema,
>({
  children,
  guestMode,
  sync,
  storage,
  AccountSchema,
  defaultProfileName,
  onLogOut,
  logOutReplacement,
  onAnonymousAccountDiscarded,
  kvStore,
  CryptoProvider,
  authSecretStorageKey,
}: JazzProviderProps<S>) {
  setupKvStore(kvStore);

  const [contextManager] = React.useState(
    () => new ReactNativeContextManager<S>({ authSecretStorageKey }),
  );

  const onLogOutRefCallback = useRefCallback(onLogOut);
  const logOutReplacementRefCallback = useRefCallback(logOutReplacement);
  const onAnonymousAccountDiscardedRefCallback = useRefCallback(
    onAnonymousAccountDiscarded,
  );
  const logoutReplacementActiveRef = useRef(false);
  logoutReplacementActiveRef.current = Boolean(logOutReplacement);

  const value = React.useSyncExternalStore<
    JazzContextType<InstanceOfSchema<S>> | undefined
  >(
    React.useCallback(
      (callback) => {
        const props = {
          AccountSchema,
          guestMode,
          sync,
          storage,
          defaultProfileName,
          onLogOut: onLogOutRefCallback,
          logOutReplacement: logoutReplacementActiveRef.current
            ? logOutReplacementRefCallback
            : undefined,
          onAnonymousAccountDiscarded: onAnonymousAccountDiscardedRefCallback,
          CryptoProvider,
        } satisfies JazzContextManagerProps<S>;

        if (contextManager.propsChanged(props)) {
          contextManager.createContext(props).catch((error) => {
            console.log(error.stack);
            console.error("Error creating Jazz React Native context:", error);
          });
        }

        return contextManager.subscribe(callback);
      },
      [sync, guestMode].concat(storage as any),
    ),
    () => contextManager.getCurrentValue(),
    () => contextManager.getCurrentValue(),
  );

  useEffect(() => {
    // In development mode we don't return a cleanup function because otherwise
    // the double effect execution would mark the context as done immediately.
    if (process.env.NODE_ENV === "development") return;

    return () => {
      contextManager.done();
    };
  }, []);

  return (
    <JazzContext.Provider value={value}>
      <JazzContextManagerContext.Provider value={contextManager}>
        {value && children}
      </JazzContextManagerContext.Provider>
    </JazzContext.Provider>
  );
}

function useRefCallback<T extends (...args: any[]) => any>(callback?: T) {
  const callbackRef = React.useRef(callback);
  callbackRef.current = callback;
  return useRef(
    (...args: Parameters<T>): ReturnType<T> => callbackRef.current?.(...args),
  ).current;
}
