// packages/jazz-tools/src/react-native-core/media/image.tsx
import { FileStream, ImageDefinition } from "jazz-tools";
import { highestResAvailable } from "jazz-tools/media";
import { forwardRef, useEffect, useMemo, useState } from "react";
import { Image as RNImage, ImageProps as RNImageProps } from "react-native";
import { useCoState } from "../hooks.js";

export type ImageProps = Omit<RNImageProps, "width" | "height" | "source"> & {
  /** The ID of the ImageDefinition to display */
  imageId: string;
  /**
   * Width of the image. Can be a number or "original" to use the original image width.
   * When set to "original", the component will calculate the appropriate height to maintain aspect ratio.
   *
   * @example
   * ```tsx
   * // Fixed width, auto-calculated height
   * <Image imageId="123" width={600} />
   *
   * // Original width
   * <Image imageId="123" width="original" />
   * ```
   */
  width?: number | "original";
  /**
   * Height of the image. Can be a number or "original" to use the original image height.
   * When set to "original", the component will calculate the appropriate width to maintain aspect ratio.
   *
   * @example
   * ```tsx
   * // Fixed height, auto-calculated width
   * <Image imageId="123" height={400} />
   *
   * // Original height
   * <Image imageId="123" height="original" />
   * ```
   */
  height?: number | "original";
  /**
   * A custom placeholder to display while an image is loading. This will
   * be passed as the src of the img tag, so a data URL works well here.
   * This will be used as a fallback if no images are ready and no placeholder
   * is available otherwise.
   */
  placeholder?: string;
};

/**
 * A React Native Image component that integrates with Jazz's ImageDefinition system.
 *
 * @example
 * ```tsx
 * import { Image } from "jazz-tools/react-native";
 * import { StyleSheet } from "react-native";
 *
 * function ProfilePicture({ imageId }) {
 *   return (
 *     <Image
 *       imageId={imageId}
 *       style={styles.profilePic}
 *       width={100}
 *       height={100}
 *       resizeMode="cover"
 *       placeholder="/placeholder.png"
 *     />
 *   );
 * }
 *
 * const styles = StyleSheet.create({
 *   profilePic: {
 *     borderRadius: 50,
 *   }
 * });
 * ```
 */
export const Image = forwardRef<RNImage, ImageProps>(function Image(
  { imageId, width, height, placeholder, ...props },
  ref,
) {
  const image = useCoState(ImageDefinition, imageId, {
    select: (image) => (image.$isLoaded ? image : null),
  });
  const [src, setSrc] = useState<string | undefined>(
    image?.placeholderDataURL ??
      "data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",
  );

  const dimensions: { width: number | undefined; height: number | undefined } =
    useMemo(() => {
      const originalWidth = image?.originalSize?.[0];
      const originalHeight = image?.originalSize?.[1];

      // Both width and height are "original"
      if (width === "original" && height === "original") {
        return { width: originalWidth, height: originalHeight };
      }

      // Width is "original", height is a number
      if (width === "original" && typeof height === "number") {
        if (originalWidth && originalHeight) {
          return {
            width: Math.round((height * originalWidth) / originalHeight),
            height,
          };
        }
        return { width: undefined, height };
      }

      // Height is "original", width is a number
      if (height === "original" && typeof width === "number") {
        if (originalWidth && originalHeight) {
          return {
            width,
            height: Math.round((width * originalHeight) / originalWidth),
          };
        }
        return { width, height: undefined };
      }

      // In all other cases, use the property value:
      return {
        width: width === "original" ? originalWidth : width,
        height: height === "original" ? originalHeight : height,
      };
    }, [image?.originalSize, width, height]);

  useEffect(() => {
    if (!image) return;

    let lastBestImage: FileStream | string | undefined =
      image?.placeholderDataURL ?? placeholder;

    const unsub = image.$jazz.subscribe({}, (update) => {
      if (lastBestImage === undefined && update.placeholderDataURL) {
        setSrc(update.placeholderDataURL);
        lastBestImage = update.placeholderDataURL;
      }

      const bestImage = highestResAvailable(
        update,
        dimensions.width || dimensions.height || 9999,
        dimensions.height || dimensions.width || 9999,
      );

      if (!bestImage) return;

      if (lastBestImage === bestImage.image) return;

      const url = bestImage.image.asBase64({ dataURL: true });

      if (url) {
        setSrc(url);
        lastBestImage = bestImage.image;
      }
    });

    return unsub;
  }, [image]);

  if (!src) {
    return null;
  }

  return (
    <RNImage
      ref={ref}
      source={{ uri: src }}
      width={dimensions.width}
      height={dimensions.height}
      {...props}
    />
  );
});

// packages/community-jazz-vue/src/Image.vue
<script setup lang="ts">
import { ImageDefinition } from "jazz-tools";
import { highestResAvailable } from "jazz-tools/media";
import { onUnmounted, ref, watch, computed } from "vue";
import { useCoState } from "./composables.js";

export interface ImageProps {
  /** The ID of the ImageDefinition to display */
  imageId: string;
  /**
   * The desired width of the image. Can be a number in pixels or "original" to use the image's original width.
   * When set to a number, the component will select the best available resolution and maintain aspect ratio.
   */
  width?: number | "original";
  /**
   * The desired height of the image. Can be a number in pixels or "original" to use the image's original height.
   * When set to a number, the component will select the best available resolution and maintain aspect ratio.
   */
  height?: number | "original";
  /** Alt text for the image */
  alt?: string;
  /** CSS classes to apply to the image */
  classNames?: string;
  /** CSS styles to apply to the image */
  style?: string | Record<string, string>;
  /** Loading strategy for the image */
  loading?: "lazy" | "eager";
}

const props = withDefaults(defineProps<ImageProps>(), {
  loading: "eager",
});

const image = useCoState(ImageDefinition, props.imageId, {});
let lastBestImage: [string, string] | null = null;

/**
 * For lazy loading, we use the browser's strategy for images with loading="lazy".
 * We use an empty image, and when the browser triggers the load event, we load the best available image.
 */
const waitingLazyLoading = ref(props.loading === "lazy");
const lazyPlaceholder = computed(() =>
  waitingLazyLoading.value ? URL.createObjectURL(emptyPixelBlob) : undefined,
);

const dimensions = computed(() => {
  const originalSize = image.value.$isLoaded
    ? image.value.originalSize
    : undefined;
  const originalWidth = originalSize?.[0];
  const originalHeight = originalSize?.[1];

  // Both width and height are "original"
  if (props.width === "original" && props.height === "original") {
    return { width: originalWidth, height: originalHeight };
  }

  // Width is "original", height is a number
  if (props.width === "original" && typeof props.height === "number") {
    if (originalWidth && originalHeight) {
      return {
        width: Math.round((props.height * originalWidth) / originalHeight),
        height: props.height,
      };
    }
    return { width: undefined, height: props.height };
  }

  // Height is "original", width is a number
  if (props.height === "original" && typeof props.width === "number") {
    if (originalWidth && originalHeight) {
      return {
        width: props.width,
        height: Math.round((props.width * originalHeight) / originalWidth),
      };
    }
    return { width: props.width, height: undefined };
  }

  // In all other cases, use the property value:
  return {
    width: props.width === "original" ? originalWidth : props.width,
    height: props.height === "original" ? originalHeight : props.height,
  };
});

const src = computed(() => {
  if (waitingLazyLoading.value) {
    return lazyPlaceholder.value;
  }

  if (!image.value.$isLoaded) return undefined;

  const bestImage = highestResAvailable(
    image.value,
    dimensions.value.width || dimensions.value.height || 9999,
    dimensions.value.height || dimensions.value.width || 9999,
  );

  if (!bestImage) return image.value.placeholderDataURL;
  if (lastBestImage?.[0] === bestImage.image.$jazz.id)
    return lastBestImage?.[1];

  const blob = bestImage.image.toBlob();

  if (blob) {
    const url = URL.createObjectURL(blob);
    revokeObjectURL(lastBestImage?.[1]);
    lastBestImage = [bestImage.image.$jazz.id, url];
    return url;
  }

  return image.value.placeholderDataURL;
});

const onThresholdReached = () => {
  waitingLazyLoading.value = false;
};

// Cleanup object URL on component destroy
onUnmounted(() => {
  revokeObjectURL(lastBestImage?.[1]);
});

function revokeObjectURL(url: string | undefined) {
  if (url && url.startsWith("blob:")) {
    URL.revokeObjectURL(url);
  }
}

const emptyPixelBlob = new Blob(
  [
    Uint8Array.from(
      atob(
        "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=",
      ),
      (c) => c.charCodeAt(0),
    ),
  ],
  { type: "image/png" },
);
</script>

<template>
  <img
    :src="src"
    :width="dimensions.width"
    :height="dimensions.height"
    :alt="alt"
    :class="classNames"
    :style="style"
    :loading="loading"
    @load="waitingLazyLoading ? onThresholdReached() : undefined"
  />
</template>
