// homepage/homepage/content/docs/code-snippets/quickstart/Festival.svelte
<script lang="ts">
  import { AccountCoState } from "jazz-tools/svelte";
  import { JazzFestAccount } from "$lib/schema";
  const me = new AccountCoState(JazzFestAccount, {
    resolve: { root: { myFestival: { $each: true } } }
  });
</script>

<ul>
  {#if me.current.$isLoaded}
    {#each me.current.root.myFestival as band}
      <li>{band.name}</li>
    {/each}
  {/if}
</ul>

// homepage/homepage/content/docs/code-snippets/quickstart/Festival.tsx
"use client";
import { useAccount } from "jazz-tools/react";
import { JazzFestAccount } from "@/app/schema";

export function Festival() {
  const me = useAccount(JazzFestAccount, {
    resolve: {
      root: {
        myFestival: {
          $each: true
        }
      }
    },
  });
  if (!me.$isLoaded) return null;
  return (
    <ul>
      {me.root.myFestival.map(
        (band) => band && <li key={band.$jazz.id}>{band.name}</li>,
      )}
    </ul>
  );
}
