// homepage/homepage/content/docs/code-snippets/key-features/authentication/quickstart/AuthWithPassphraseLogin.tsx
import { useState } from "react";
import { usePasskeyAuth, usePassphraseAuth } from "jazz-tools/react";
import { wordlist } from "./wordlist"; // or the path to your wordlist

export function Auth({ children }: { children: React.ReactNode }) {
  const [name, setName] = useState("");
  // [!code ++:1]
  const [passphraseInput, setPassphraseInput] = useState("");

  const auth = usePasskeyAuth({
    // Must be inside the JazzProvider because the hook depends on an active Jazz context.
    appName: "JazzFest",
  });

  const passphraseAuth = usePassphraseAuth({ wordlist }); // This should be inside the provider too

  return (
    <>
      <div>
        <button onClick={() => auth.logIn()}>Log in</button>
        <input
          type="text"
          value={name}
          onChange={(e) => setName(e.target.value)}
        />
        <button onClick={() => auth.signUp(name)}>Sign up</button>
      </div>
      {auth.state === "signedIn" && (
        <>
          {children}
          <textarea readOnly value={passphraseAuth.passphrase} rows={5} />
        </>
      )}
      {/* [!code ++:8]*/}
      {auth.state !== "signedIn" && (
        <>
          <textarea
            onChange={(e) => setPassphraseInput(e.target.value)}
            rows={5}
          />
          <button onClick={() => passphraseAuth.logIn(passphraseInput)}>
            Sign In with Passphrase
          </button>
        </>
      )}
    </>
  );
}

// homepage/homepage/content/docs/code-snippets/key-features/authentication/quickstart/AuthWithPassphraseLogin.svelte
<script lang="ts">
  import { usePasskeyAuth, usePassphraseAuth } from 'jazz-tools/svelte';
  import { wordlist } from './wordlist';
  const { children } = $props();
  const passphraseAuth = usePassphraseAuth({ wordlist });
  const auth = usePasskeyAuth({ appName: 'JazzFest' });
  let name = $state('');
  // [!code ++:1]
  let passphrase = $state('');
</script>

{#if auth.state === "signedIn"}
  {@render children?.()}
  <textarea
    readonly
    value={passphraseAuth.passphrase}
    rows={5}
  ></textarea>
{:else}
  <div>
    <button onclick={() => auth.current.logIn()}>Log in</button>
    <input type="text" bind:value={name} />
    <button onclick={() => auth.current.signUp(name)}>Sign up</button>
    <!-- [!code ++:7] -->
    <textarea
      bind:value={passphrase}
      rows={5}
    ></textarea>
    <button onclick={() => passphraseAuth.logIn(passphrase)}>
      Sign In with Passphrase
    </button>
  </div>
{/if}
