// homepage/homepage/content/docs/code-snippets/key-features/authentication/quickstart/Auth.tsx
import { useState } from "react";
import { usePasskeyAuth } from "jazz-tools/react";

export function Auth({ children }: { children: React.ReactNode }) {
  const [name, setName] = useState("");

  const auth = usePasskeyAuth({
    // Must be inside the JazzProvider because the hook depends on an active Jazz context.
    appName: "JazzFest",
  });

  return (
    <>
      <div>
        <button onClick={() => auth.logIn()}>Log in</button>
        <input
          type="text"
          value={name}
          onChange={(e) => setName(e.target.value)}
        />
        <button onClick={() => auth.signUp(name)}>Sign up</button>
      </div>
      {auth.state === "signedIn" && children}
    </>
  );
}

// homepage/homepage/content/docs/code-snippets/key-features/authentication/quickstart/Auth.svelte
<script lang="ts">
  import { usePasskeyAuth } from 'jazz-tools/svelte';
  const { children } = $props();
  const auth = usePasskeyAuth({ appName: 'JazzFest' });
  let name = $state('');
</script>

{#if auth.state === "signedIn"}
  {@render children?.()}
{:else}
  <div>
    <button onclick={() => auth.current.logIn()}>Log in</button>
    <input type="text" bind:value={name} />
    <button onclick={() => auth.current.signUp(name)}>Sign up</button>
  </div>
{/if}
