// homepage/homepage/content/docs/code-snippets/server-side/ssr/+page.svelte
<script lang="ts">
  import { jazzSSR } from "$lib/jazzSSR";
  import { Festival } from "$lib/schema";
  // @ts-expect-error Only available in a real SK app
  import { page } from '$app/state';

	const festivalId = $derived(page.params.festivalId);

  const festival = $derived(Festival.load(festivalId, {
    loadAs: jazzSSR,
    resolve: {
      $each: {
        $onError: 'catch',
      },
    },
  }));
</script>

<main>
  <h1>🎪 Server-rendered Festival {festivalId}</h1>
  <ul>
    {#await festival then festival}
      {#each festival.$isLoaded ? festival : [] as band (band.$jazz.id)}
        {#if band.$isLoaded}
          <li>🎶 {band.name}</li>
        {/if}
      {/each}
    {/await}
  </ul>
</main>

// homepage/homepage/content/docs/code-snippets/server-side/ssr/page.tsx
import { jazzSSR } from "@/app/jazzSSR";
import { Festival } from "@/app/schema";

export default async function ServerSidePage(props: {
  params: { festivalId: string };
}) {
  const { festivalId } = await props.params;
  const festival = await Festival.load(festivalId, {
    loadAs: jazzSSR,
    resolve: {
      $each: {
        $onError: "catch",
      },
    },
  });

  return (
    <main>
      <h1>🎪 Server-rendered Festival {festivalId}</h1>

      <ul>
        {festival.$isLoaded &&
          festival.map((band) => {
            if (!band.$isLoaded) return null;
            return <li key={band.$jazz.id}>🎶 {band.name}</li>;
          })}
      </ul>
    </main>
  );
}
