// homepage/homepage/content/docs/code-snippets/core-concepts/schemas/accounts-and-migrations/DashboardPageComponent.tsx
import * as React from "react";
import { co, z } from "jazz-tools";
import { MyAppAccount } from "./schema";

const Chat = co.map({});

class ChatPreview extends React.Component<{ chat: co.loaded<typeof Chat> }> {}

// #region Main
import { useAccount } from "jazz-tools/react";

function DashboardPageComponent() {
  const me = useAccount(MyAppAccount, {
    resolve: {
      profile: true,
      root: {
        myChats: { $each: true },
      },
    },
  });

  return (
    <div>
      <h1>Dashboard</h1>
      {me.$isLoaded ? (
        <div>
          <p>Logged in as {me.profile.name}</p>
          <h2>My chats</h2>
          {me.root.myChats.map((chat) => (
            <ChatPreview key={chat.$jazz.id} chat={chat} />
          ))}
        </div>
      ) : (
        "Loading..."
      )}
    </div>
  );
}
// #endregion

// homepage/homepage/content/docs/code-snippets/core-concepts/schemas/accounts-and-migrations/DashboardPageComponent.svelte
<script lang="ts">
  import { AccountCoState } from "jazz-tools/svelte";
  import { MyAppAccount } from "./schema";
  import ChatPreview from "./ChatPreview.svelte";
  const me = new AccountCoState(MyAppAccount, {
    resolve: {
      profile: true,
      root: {
        myChats: { $each: true },
      },
    },
  });
</script>

    <div>
      <h1>Dashboard</h1>
      {#if me.current?.$isLoaded}
        <div>
          <p>Logged in as {me.current.profile.name}</p>
          <h2>My chats</h2>
          {#each me.current.root.myChats as chat (chat.$jazz.id)}
            <ChatPreview id={chat.$jazz.id} />
          {/each}
        </div>
        {:else}
        <div>Loading...</div>
        {/if}
    </div>
  );
}
