// homepage/homepage/content/docs/code-snippets/server-side/quickstart/+page.svelte
<script lang="ts">
  import type { co } from "jazz-tools";
  import { announceBand } from "$lib/announceBandSchema.svelte.ts";
  import type { BandList } from "./schema";
  let bandName = $state("");
  let bandList = $state<co.loaded<typeof BandList, { $each: true }>>();
  async function handleAnnounceBand() {
    const bandListResponse = await announceBand.send({
      band: { name: bandName },
    });
    bandName = "";
    if (bandListResponse.bandList) {
      bandList = bandListResponse.bandList;
    }
  }
</script>

<div>
  <input type="text" bind:value={bandName} />
  <button type="button" onclick={handleAnnounceBand}> Announce Band </button>
  <div>
    {#if bandList?.$isLoaded}
      {#each bandList as band (band?.$jazz.id)}
        <div>{band.name}</div>
      {/each}
    {/if}
  </div>
</div>

// homepage/homepage/content/docs/code-snippets/server-side/quickstart/page.tsx
"use client";
import type { co } from "jazz-tools";
import { useState } from "react";
import { announceBand } from "@/app/announceBandSchema";
import type { BandList } from "./schema";

export default function Home() {
  const [bandName, setBandName] = useState("");
  const [bandList, setBandList] =
    useState<co.loaded<typeof BandList, { $each: true }>>();
  const handleAnnounceBand = async () => {
    const bandListResponse = await announceBand.send({
      band: { name: bandName },
    });
    setBandName("");
    if (bandListResponse.bandList.$isLoaded) {
      setBandList(bandListResponse.bandList);
    }
  };

  return (
    <div>
      <input
        type="text"
        value={bandName}
        onChange={(e) => setBandName(e.target.value)}
      />
      <button type="button" onClick={handleAnnounceBand}>
        Announce Band
      </button>
      <div>
        {bandList?.$isLoaded &&
          bandList.map(
            (band) => band && <div key={band?.$jazz.id}>{band.name}</div>,
          )}
      </div>
    </div>
  );
}
