// examples/inspector/src/viewer/value-renderer.tsx
import clsx from "clsx";
import { CoID, JsonValue, LocalNode, RawCoValue } from "cojson";
import React, { useEffect, useState } from "react";
import { LinkIcon } from "../link-icon";
import {
  isBrowserImage,
  resolveCoValue,
  useResolvedCoValue,
} from "./use-resolve-covalue";

// Is there a chance we can pass the actual CoValue here?
export function ValueRenderer({
  json,
  compact,
  onCoIDClick,
}: {
  json: JsonValue | undefined;
  compact?: boolean;
  onCoIDClick?: (childNode: CoID<RawCoValue>) => void;
}) {
  const [isExpanded, setIsExpanded] = useState(false);

  if (typeof json === "undefined" || json === undefined) {
    return <span className="text-gray-400">undefined</span>;
  }

  if (json === null) {
    return <span className="text-gray-400">null</span>;
  }

  if (typeof json === "string" && json.startsWith("co_")) {
    return (
      <span
        className={clsx(
          "inline-flex gap-1 items-center",
          onCoIDClick && "text-blue-500 cursor-pointer hover:underline",
        )}
        onClick={() => {
          onCoIDClick?.(json as CoID<RawCoValue>);
        }}
      >
        {json}
        {onCoIDClick && <LinkIcon />}
      </span>
    );
  }

  if (typeof json === "string") {
    return (
      <span className="text-green-900 font-mono">
        {/* <span className="select-none opacity-70">{'"'}</span> */}
        {json}
        {/* <span className="select-none opacity-70">{'"'}</span> */}
      </span>
    );
  }

  if (typeof json === "number") {
    return <span className="text-purple-500">{json}</span>;
  }

  if (typeof json === "boolean") {
    return (
      <span
        className={clsx(
          json
            ? "text-green-700 bg-green-700/5"
            : "text-amber-700 bg-amber-500/5",
          "font-mono",
          "inline-block px-1 py-0.5 rounded",
        )}
      >
        {json.toString()}
      </span>
    );
  }

  if (Array.isArray(json)) {
    return (
      <span title={JSON.stringify(json)}>
        Array <span className="text-gray-500">({json.length})</span>
      </span>
    );
  }

  if (typeof json === "object") {
    return (
      <span
        title={JSON.stringify(json, null, 2)}
        className="inline-block max-w-64"
      >
        {compact ? (
          <span>
            Object{" "}
            <span className="text-gray-500">({Object.keys(json).length})</span>
            <pre className="mt-1 text-sm whitespace-pre-wrap">
              {isExpanded
                ? JSON.stringify(json, null, 2)
                : JSON.stringify(json, null, 2)
                    .split("\n")
                    .slice(0, 3)
                    .join("\n") + (Object.keys(json).length > 2 ? "\n..." : "")}
            </pre>
            <button
              onClick={() => setIsExpanded(!isExpanded)}
              className="text-xs text-gray-500 hover:text-gray-700"
            >
              {isExpanded ? "Show less" : "Show more"}
            </button>
          </span>
        ) : (
          <pre className="whitespace-pre-wrap">
            {JSON.stringify(json, null, 2)}
          </pre>
        )}
      </span>
    );
  }

  return <span>{String(json)}</span>;
}

export const CoMapPreview = ({
  coId,
  node,
  limit = 6,
}: {
  coId: CoID<RawCoValue>;
  node: LocalNode;
  limit?: number;
}) => {
  const { value, snapshot, type, extendedType } = useResolvedCoValue(
    coId,
    node,
  );

  if (!snapshot) {
    return (
      <div className="rounded bg-gray-100 animate-pulse whitespace-pre w-24">
        {" "}
      </div>
    );
  }

  if (snapshot === "unavailable" && !value) {
    return <div className="text-gray-500">Unavailable</div>;
  }

  if (extendedType === "image" && isBrowserImage(snapshot)) {
    return (
      <div>
        <img
          src={snapshot.placeholderDataURL}
          className="size-8 border-2 border-white drop-shadow-md my-2"
        />
        <span className="text-gray-500 text-sm">
          {snapshot.originalSize[0]} x {snapshot.originalSize[1]}
        </span>

        {/* <CoMapPreview coId={value[]} node={node} /> */}
        {/* <ProgressiveImg image={value}>
                    {({ src }) => <img src={src} className={clsx("w-full")} />}
                </ProgressiveImg> */}
      </div>
    );
  }

  if (extendedType === "record") {
    return (
      <div>
        Record{" "}
        <span className="text-gray-500">({Object.keys(snapshot).length})</span>
      </div>
    );
  }

  if (type === "colist") {
    return (
      <div>
        List{" "}
        <span className="text-gray-500">
          ({(snapshot as unknown as []).length})
        </span>
      </div>
    );
  }

  return (
    <div className="text-sm flex flex-col gap-2 items-start">
      <div className="grid grid-cols-[auto_1fr] gap-2">
        {Object.entries(snapshot)
          .slice(0, limit)
          .map(([key, value]) => (
            <React.Fragment key={key}>
              <span className="font-medium">{key}: </span>
              <span>
                <ValueRenderer json={value} />
              </span>
            </React.Fragment>
          ))}
      </div>
      {Object.entries(snapshot).length > limit && (
        <div className="text-left text-xs text-gray-500 mt-2">
          {Object.entries(snapshot).length - limit} more
        </div>
      )}
    </div>
  );
};

export function AccountOrGroupPreview({
  coId,
  node,
  showId = false,
  onClick,
}: {
  coId: CoID<RawCoValue>;
  node: LocalNode;
  showId?: boolean;
  onClick?: (name?: string) => void;
}) {
  const { snapshot, extendedType } = useResolvedCoValue(coId, node);
  const [name, setName] = useState<string | null>(null);

  useEffect(() => {
    if (extendedType === "account") {
      resolveCoValue(
        (snapshot as unknown as { profile: CoID<RawCoValue> }).profile,
        node,
      ).then(({ snapshot }) => {
        if (
          typeof snapshot === "object" &&
          "name" in snapshot &&
          typeof snapshot.name === "string"
        ) {
          setName(snapshot.name);
        }
      });
    }
  }, [snapshot, node, extendedType]);

  if (!snapshot) return <span>Loading...</span>;
  if (extendedType !== "account" && extendedType !== "group") {
    return <span>CoID is not an account or group</span>;
  }

  const displayName = extendedType === "account" ? name || "Account" : "Group";
  const displayText = showId ? `${displayName} (${coId})` : displayName;

  const props = onClick
    ? {
        onClick: () => onClick(displayName),
        className: "text-blue-500 cursor-pointer hover:underline",
      }
    : {
        className: "text-gray-500",
      };

  return <span {...props}>{displayText}</span>;
}

// packages/community-jazz-vue/src/inspector/viewer/value-renderer.tsx
import { CoID, JsonValue, LocalNode, RawCoValue } from "cojson";
import { styled } from "goober";
import { Fragment, type PropType, defineComponent, ref } from "vue";
import { Button } from "../ui/button.js";
import { Icon } from "../ui/icon.js";
import { Text } from "../ui/text.js";
import { isCoId } from "./types.js";
import { isBrowserImage, useResolvedCoValue } from "./use-resolve-covalue.js";

const LinkContainer = styled("span")`
  display: inline-flex;
  gap: 0.25rem;
  align-items: center;
`;

const BooleanText = styled("span")<{ value: boolean }>`
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
  ${(props) =>
    props.value
      ? `
    color: var(--j-success-color);
  `
      : `
    color: var(--j-destructive-color);
  `}
`;

const ObjectContent = styled("pre")`
  margin-top: 0.375rem;
  font-size: 0.875rem;
  white-space: pre-wrap;
`;

const PreviewContainer = styled("div")`
  font-size: 0.875rem;
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
  align-items: flex-start;
`;

const PreviewGrid = styled("div")`
  display: grid;
  grid-template-columns: auto 1fr;
  gap: 0.5rem;
`;

const PreviewMoreText = styled("span")`
  text-align: left;
  margin-top: 0.5rem;
  color: #6b7280;
  font-size: 0.875rem;
`;

const ImagePreviewContainer = styled("div")`
  display: flex;
  flex-direction: column;
  align-items: flex-start;
`;

const PreviewImage = styled("img")`
  width: 2rem;
  height: 2rem;
  border: 2px solid white;
  box-shadow: var(--j-shadow-sm);
  margin: 0.5rem 0;
`;

const RecordText = styled("div")`
  display: flex;
  align-items: center;
  gap: 0.25rem;
`;

const ListText = styled("div")`
  display: flex;
  align-items: center;
  gap: 0.25rem;
`;

export const ValueRenderer = defineComponent({
  name: "ValueRenderer",
  props: {
    json: {
      type: [String, Number, Boolean, Object, Array] as PropType<
        JsonValue | undefined
      >,
      required: false,
    },
    onCoIDClick: {
      type: Function as PropType<(childNode: CoID<RawCoValue>) => void>,
      required: false,
    },
    compact: {
      type: Boolean,
      default: false,
    },
  },
  setup(props) {
    const isExpanded = ref(false);

    return () => {
      const { json, onCoIDClick, compact } = props;

      if (typeof json === "undefined" || json === undefined) {
        return <Text muted>undefined</Text>;
      }

      if (json === null) {
        return <Text muted>null</Text>;
      }

      if (typeof json === "string" && isCoId(json)) {
        const content = (
          <>
            {json}
            {onCoIDClick && <Icon name="link" />}
          </>
        );

        if (onCoIDClick) {
          return (
            <Button
              variant="link"
              onClick={() => {
                onCoIDClick?.(json as CoID<RawCoValue>);
              }}
            >
              {content}
            </Button>
          );
        }

        return <LinkContainer>{content}</LinkContainer>;
      }

      if (typeof json === "string") {
        return <Text>{json}</Text>;
      }

      if (typeof json === "number") {
        return <Text mono>{json}</Text>;
      }

      if (typeof json === "boolean") {
        return <BooleanText value={json}>{json.toString()}</BooleanText>;
      }

      const longJson = JSON.stringify(json, null, 2);
      const shortJson = longJson
        .split("\n")
        .slice(0, compact ? 3 : 8)
        .join("\n");

      // Check if collapsed differs from full
      const hasDifference = longJson !== shortJson;

      if (typeof json === "object") {
        return (
          <>
            <p>
              {Array.isArray(json) ? <>Array ({json.length})</> : <>Object</>}
            </p>
            <ObjectContent>
              {isExpanded.value ? longJson : shortJson}

              {hasDifference && !isExpanded.value ? "\n ..." : null}
            </ObjectContent>

            {!compact && hasDifference ? (
              <Button
                variant="link"
                onClick={() => (isExpanded.value = !isExpanded.value)}
              >
                {isExpanded.value ? "Show less" : "Show more"}
              </Button>
            ) : null}
          </>
        );
      }

      return <span>{String(json)}</span>;
    };
  },
});

export const CoMapPreview = defineComponent({
  name: "CoMapPreview",
  props: {
    coId: {
      type: String as any,
      required: true,
    },
    node: {
      type: Object as PropType<LocalNode>,
      required: true,
    },
    limit: {
      type: Number,
      default: 6,
    },
  },
  setup(props) {
    const { value, snapshot, type, extendedType } = useResolvedCoValue(
      props.coId,
      props.node,
    );

    return () => {
      if (!snapshot.value) {
        return (
          <div
            style={{
              borderRadius: "0.25rem",
              backgroundColor: "var(--j-foreground)",
              animation: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
              whiteSpace: "pre",
              width: "6rem",
            }}
          >
            {" "}
          </div>
        );
      }

      if (snapshot.value === "unavailable" && !value.value) {
        return (
          <Text inline muted>
            Unavailable
          </Text>
        );
      }

      if (type.value === "coplaintext") {
        return <>{value.value?.toString()}</>;
      }

      if (
        extendedType.value === "image" &&
        snapshot.value &&
        typeof snapshot.value === "object" &&
        isBrowserImage(snapshot.value as any)
      ) {
        return (
          <ImagePreviewContainer>
            <PreviewImage
              src={(snapshot.value as any).placeholderDataURL || ""}
            />
            <Text inline small muted>
              {(snapshot.value as any).originalSize?.[0]} x{" "}
              {(snapshot.value as any).originalSize?.[1]}
            </Text>
          </ImagePreviewContainer>
        );
      }

      if (extendedType.value === "record") {
        return (
          <RecordText>
            Record{" "}
            <Text inline muted>
              ({Object.keys(snapshot.value).length})
            </Text>
          </RecordText>
        );
      }

      if (type.value === "colist") {
        return (
          <ListText>
            List{" "}
            <Text inline muted>
              ({(snapshot.value as unknown as []).length})
            </Text>
          </ListText>
        );
      }

      const properties = Object.entries(snapshot.value);
      const limitedProperties =
        extendedType.value === "account"
          ? properties
              .filter(
                ([key]) =>
                  !key.startsWith("key_z") &&
                  !key.startsWith("sealer_z") &&
                  key !== "readKey",
              )
              .slice(0, props.limit)
          : properties.slice(0, props.limit);

      return (
        <PreviewContainer>
          <PreviewGrid>
            {limitedProperties.map(([key, value]) => (
              <Fragment key={key}>
                <Text strong>{key}: </Text>
                <ValueRenderer compact json={value} />
              </Fragment>
            ))}
          </PreviewGrid>
          {properties.length > props.limit && (
            <PreviewMoreText>
              {properties.length - props.limit} more
            </PreviewMoreText>
          )}
        </PreviewContainer>
      );
    };
  },
});
