// packages/jazz-tools/src/inspector/ui/table.tsx
import { styled } from "goober";
import React from "react";

const StyledTable = styled("table")`
  width: 100%;
`;

const StyledThead = styled("thead")`
  text-align: left;
  border-bottom: 1px solid var(--j-border-color);
  background-color: var(--j-neutral-100);

  @media (prefers-color-scheme: dark) {
    background-color: var(--j-neutral-925);
  }
`;

const StyledTbody = styled("tbody")`
  tr {
    border-bottom: 1px solid var(--j-border-color);

    &:last-child {
      border-bottom: none;
    }
  }
`;

const StyledTh = styled("th")`
  font-weight: 500;
  padding: 0.5rem 0.75rem;
  color: var(--j-text-color-strong);
`;

const StyledTd = styled("td")`
  padding: 0.5rem 0.75rem;
`;

export const Table = React.forwardRef<
  HTMLTableElement,
  React.HTMLAttributes<HTMLTableElement>
>(({ children, ...props }, ref) => (
  <StyledTable ref={ref} {...props}>
    {children}
  </StyledTable>
));

export const TableHead = React.forwardRef<
  HTMLTableSectionElement,
  React.HTMLAttributes<HTMLTableSectionElement>
>(({ children, ...props }, ref) => (
  <StyledThead ref={ref} {...props}>
    {children}
  </StyledThead>
));

export const TableBody = React.forwardRef<
  HTMLTableSectionElement,
  React.HTMLAttributes<HTMLTableSectionElement>
>(({ children, ...props }, ref) => (
  <StyledTbody ref={ref} {...props}>
    {children}
  </StyledTbody>
));

export const TableRow = React.forwardRef<
  HTMLTableRowElement,
  React.HTMLAttributes<HTMLTableRowElement>
>(({ children, ...props }, ref) => (
  <tr ref={ref} {...props}>
    {children}
  </tr>
));

export const TableHeader = React.forwardRef<
  HTMLTableCellElement,
  React.ThHTMLAttributes<HTMLTableCellElement>
>(({ children, ...props }, ref) => (
  <StyledTh ref={ref} {...props}>
    {children}
  </StyledTh>
));

export const TableCell = React.forwardRef<
  HTMLTableCellElement,
  React.TdHTMLAttributes<HTMLTableCellElement>
>(({ children, ...props }, ref) => (
  <StyledTd ref={ref} {...props}>
    {children}
  </StyledTd>
));

// packages/community-jazz-vue/src/inspector/ui/table.tsx
import { styled } from "goober";
import { defineComponent } from "vue";

const StyledTable = styled("table")`
  width: 100%;
`;

const StyledThead = styled("thead")`
  text-align: left;
  border-bottom: 1px solid var(--j-border-color);
  background-color: var(--j-neutral-100);

  @media (prefers-color-scheme: dark) {
    background-color: var(--j-neutral-925);
  }
`;

const StyledTbody = styled("tbody")`
  tr {
    border-bottom: 1px solid var(--j-border-color);

    &:last-child {
      border-bottom: none;
    }
  }
`;

const StyledTh = styled("th")`
  font-weight: 500;
  padding: 0.5rem 0.75rem;
  color: var(--j-text-color-strong);
`;

const StyledTd = styled("td")`
  padding: 0.5rem 0.75rem;
`;

export const Table = defineComponent({
  name: "Table",
  props: {
    class: String,
    style: [String, Object],
  },
  setup(props, { slots, attrs }) {
    return () => (
      <StyledTable
        {...attrs}
        className={props.class}
        style={props.style as any}
      >
        {slots.default?.()}
      </StyledTable>
    );
  },
});

export const TableHead = defineComponent({
  name: "TableHead",
  props: {
    class: String,
    style: [String, Object],
  },
  setup(props, { slots, attrs }) {
    return () => (
      <StyledThead
        {...attrs}
        className={props.class}
        style={props.style as any}
      >
        {slots.default?.()}
      </StyledThead>
    );
  },
});

export const TableBody = defineComponent({
  name: "TableBody",
  props: {
    class: String,
    style: [String, Object],
  },
  setup(props, { slots, attrs }) {
    return () => (
      <StyledTbody
        {...attrs}
        className={props.class}
        style={props.style as any}
      >
        {slots.default?.()}
      </StyledTbody>
    );
  },
});

export const TableRow = defineComponent({
  name: "TableRow",
  props: {
    class: String,
    style: [String, Object],
  },
  setup(props, { slots, attrs }) {
    return () => (
      <tr {...attrs} class={props.class} style={props.style as any}>
        {slots.default?.()}
      </tr>
    );
  },
});

export const TableHeader = defineComponent({
  name: "TableHeader",
  props: {
    class: String,
    style: [String, Object],
  },
  setup(props, { slots, attrs }) {
    return () => (
      <StyledTh {...attrs} className={props.class} style={props.style as any}>
        {slots.default?.()}
      </StyledTh>
    );
  },
});

export const TableCell = defineComponent({
  name: "TableCell",
  props: {
    class: String,
    style: [String, Object],
  },
  setup(props, { slots, attrs }) {
    return () => (
      <StyledTd {...attrs} className={props.class} style={props.style as any}>
        {slots.default?.()}
      </StyledTd>
    );
  },
});
