// packages/jazz-svelte/src/lib/Provider.svelte
<script lang="ts" module>
  export type Props<Acc extends Account = Account> = {
    children?: Snippet;
    guestMode?: boolean;
    localOnly?: 'always' | 'anonymous' | 'off';
    peer: `wss://${string}` | `ws://${string}`;
    storage?: 'indexedDB' | 'singleTabOPFS';
    AccountSchema?: AccountClass<Acc>;
  };
</script>

<script lang="ts" generics="Acc extends Account">
  import { JazzContextManager } from 'jazz-browser';
  import type { AccountClass } from 'jazz-tools';
  import { Account } from 'jazz-tools';
  import { type Snippet, setContext, untrack } from 'svelte';
  import { JAZZ_CTX, type JazzContext } from './jazz.svelte.js';
  import { useIsAnonymousUser } from './auth/useAnonymousUser.svelte.js';

  let props: Props<Acc> = $props();

  const contextManager = new JazzContextManager<Acc>();

  const ctx = $state<JazzContext<Acc>>({ current: undefined });
  setContext<JazzContext<Acc>>(JAZZ_CTX, ctx);

  const isAnonymousUser = useIsAnonymousUser();
  const localOnly = $derived(
    props.localOnly === 'anonymous' ? isAnonymousUser.value : props.localOnly === 'always'
  );

  $effect(() => {
    props.peer;
    props.storage;
    return untrack(() => {
      if (!props.peer) return;

      contextManager
        .createContext({
          peer: props.peer,
          storage: props.storage,
          guestMode: props.guestMode,
          AccountSchema: props.AccountSchema,
          localOnly: localOnly
        })
        .catch((error) => {
          console.error('Error creating Jazz browser context:', error);
        });
    });
  });

  $effect(() => {
    contextManager.toggleNetwork(!localOnly);
  });

  $effect(() => {
    return contextManager.subscribe(() => {
      ctx.current = contextManager.getCurrentValue();
    });
  });
</script>

{#if ctx.current}
  {@render props.children?.()}
{/if}

// packages/jazz-react/src/provider.tsx
import { JazzContextManager, JazzContextManagerProps } from "jazz-browser";
import React, { useEffect } from "react";

import { JazzContext } from "jazz-react-core";
import { Account, JazzContextType } from "jazz-tools";
import { useIsAnonymousUser } from "./auth/AnonymousAuth.js";

export interface Register {}

export type RegisteredAccount = Register extends { Account: infer Acc }
  ? Acc
  : Account;

export type JazzProviderProps<Acc extends Account = RegisteredAccount> = {
  children: React.ReactNode;
  localOnly?: "always" | "anonymous" | "off";
} & Omit<JazzContextManagerProps<Acc>, "localOnly">;

/** @category Context & Hooks */
export function JazzProvider<Acc extends Account = RegisteredAccount>({
  children,
  guestMode,
  peer,
  storage,
  AccountSchema,
  localOnly: localOnlyProp,
}: JazzProviderProps<Acc>) {
  const [contextManager] = React.useState(() => new JazzContextManager<Acc>());

  const isAnonymousUser = useIsAnonymousUser();
  const localOnly =
    localOnlyProp === "anonymous"
      ? isAnonymousUser
      : localOnlyProp === "always";

  const value = React.useSyncExternalStore<JazzContextType<Acc> | undefined>(
    React.useCallback(
      (callback) => {
        const props = { AccountSchema, guestMode, peer, storage, localOnly };
        if (contextManager.propsChanged(props)) {
          contextManager.createContext(props).catch((error) => {
            console.error("Error creating Jazz browser context:", error);
          });
        }

        return contextManager.subscribe(callback);
      },
      [peer].concat(storage as any),
    ),
    () => contextManager.getCurrentValue(),
    () => contextManager.getCurrentValue(),
  );

  useEffect(() => {
    // In development mode we don't return a cleanup function because otherwise
    // the double effect execution would mark the context as done immediately.
    if (process.env.NODE_ENV === "development") return;

    return () => {
      contextManager.done();
    };
  }, []);

  useEffect(() => {
    contextManager.toggleNetwork(!localOnly);
  }, [value, localOnly]);

  return (
    <JazzContext.Provider value={value}>
      {value && children}
    </JazzContext.Provider>
  );
}
