// homepage/homepage/content/docs/code-snippets/core-concepts/subscription-and-loading/ProjectList.tsx
import { useAccount } from "jazz-tools/react";
import { MyAppAccount } from "./schema";

function ProjectList() {
  const me = useAccount(MyAppAccount, {
    resolve: { profile: true },
  });

  if (!me.$isLoaded) {
    return "Loading...";
  }

  return (
    <div>
      <h1>{me.profile.name}'s projects</h1>
    </div>
  );
}

// homepage/homepage/content/docs/code-snippets/core-concepts/subscription-and-loading/ProjectList.svelte

<script lang="ts">
  import { AccountCoState } from "jazz-tools/svelte";
  import { MyAppAccount } from "./schema";
  const account = new AccountCoState(MyAppAccount, {
    resolve: { profile: true }
  });
</script>

{#if !account.current.$isLoaded}
  Loading...
{:else}
  <div>
    <h1>{account.current.profile.name}'s projects</h1>
  </div>
{/if}
