// homepage/homepage/content/docs/code-snippets/permissions-and-sharing/quickstart/FestivalWithAccept.tsx
"use client";
// @ts-expect-error Duplicate import
import { createInviteLink, useAccount } from "jazz-tools/react";
// [!code ++:2]
import {
  // @ts-expect-error Duplicate import
  createInviteLink,
  useAcceptInvite,
  // @ts-expect-error Duplicate import
  useAccount,
} from "jazz-tools/react";
import { useRouter } from "next/navigation";
import { useState } from "react";
// [!code --:1]
// @ts-expect-error Duplicate import
import { JazzFestAccount } from "@/app/schema";
// [!code ++:2]
// We need to alias the schema because our component is also named Festival
// @ts-expect-error Duplicate import
import { Festival as FestivalSchema, JazzFestAccount } from "@/app/schema";

export function Festival() {
  const [inviteLink, setInviteLink] = useState<string>("");
  const me = useAccount(JazzFestAccount, {
    resolve: { root: { myFestival: { $each: true } } },
  });
  // [!code ++:7]
  const router = useRouter();
  useAcceptInvite({
    invitedObjectSchema: FestivalSchema,
    onAccept: (festivalID: string) => {
      router.push(`/festival/${festivalID}`);
    },
  });
  if (!me.$isLoaded) return null;

  const inviteLinkClickHandler = () => {
    const link = createInviteLink(me.root.myFestival, "writer");
    setInviteLink(link);
  };
  return (
    <>
      <ul>
        {me.root.myFestival.map((band) => (
          <li key={band.$jazz.id}>{band.name}</li>
        ))}
      </ul>
      <input type="text" value={inviteLink} readOnly />
      <button onClick={inviteLinkClickHandler}>Create Invite Link</button>
    </>
  );
}

// homepage/homepage/content/docs/code-snippets/permissions-and-sharing/quickstart/FestivalWithAccept.svelte
<script lang="ts">
  // [!code ++:3]
  import { AccountCoState, createInviteLink, InviteListener } from "jazz-tools/svelte";
  // @ts-expect-error Not available outside SK app
  import { goto } from "$app/navigation";
  import { Festival, JazzFestAccount } from "$lib/schema";

  const me = new AccountCoState(JazzFestAccount, {
    resolve: { root: { myFestival: { $each: true } } }
  });
  let inviteLink = $state<string | null>(null);

  // [!code ++:6]
  new InviteListener({
		invitedObjectSchema: Festival,
		onAccept: (festivalID) => {
			goto(`/festival/${festivalID}`);
		}
	});

  function inviteLinkClickHandler() {
    if (!me.current.$isLoaded) return;
    const link = createInviteLink(me.current?.root.myFestival, "writer")
    inviteLink = link;
  }
</script>

<ul>
  {#if me.current.$isLoaded}
    {#each me.current.root.myFestival as band}
      <li>{band.name}</li>
    {/each}
  {/if}
</ul>

<input type="text" bind:value={inviteLink} readonly />
<button onclick={inviteLinkClickHandler}>
  Create Invite Link
</button>
