// homepage/homepage/content/docs/code-snippets/permissions-and-sharing/quickstart/FestivalWithoutProp.svelte
<script lang="ts">
  // [!code ++:1]
  import { AccountCoState, createInviteLink } from "jazz-tools/svelte";
  import { JazzFestAccount } from "$lib/schema";

  const me = new AccountCoState(JazzFestAccount, {
    resolve: { root: { myFestival: { $each: true } } }
  });
  // [!code ++:7]
  let inviteLink = $state<string | null>(null);

  function inviteLinkClickHandler() {
    if (!me.current.$isLoaded) return;
    const link = createInviteLink(me.current?.root.myFestival, "writer")
    inviteLink = link;
  }
</script>

<ul>
  {#if me.current.$isLoaded}
    {#each me.current.root.myFestival as band}
      <li>{band.name}</li>
    {/each}
  {/if}
</ul>

<input type="text" bind:value={inviteLink} readonly />
<button onclick={inviteLinkClickHandler}>
  Create Invite Link
</button>

// homepage/homepage/content/docs/code-snippets/permissions-and-sharing/quickstart/FestivalWithoutProp.tsx
"use client";
// [!code --:1]
// @ts-expect-error Duplicate import
import { useAccount } from "jazz-tools/react";
// [!code ++:1]
// @ts-expect-error Duplicate import
import { createInviteLink, useAccount } from "jazz-tools/react";
// [!code ++:1]
import { useState } from "react";
import { JazzFestAccount } from "@/app/schema";

export function Festival() {
  // [!code ++:1]
  const [inviteLink, setInviteLink] = useState<string>("");
  const me = useAccount(JazzFestAccount, {
    resolve: { root: { myFestival: { $each: true } } },
  });
  if (!me.$isLoaded) return null;
  // [!code ++:4]
  const inviteLinkClickHandler = () => {
    const link = createInviteLink(me.root.myFestival, "writer");
    setInviteLink(link);
  };
  return (
    // [!code ++:1]
    <>
      <ul>
        {me.root.myFestival.map((band) => (
          <li key={band.$jazz.id}>{band.name}</li>
        ))}
      </ul>
      {/* [!code ++:5] */}
      <input type="text" value={inviteLink} readOnly />
      <button onClick={inviteLinkClickHandler}>Create Invite Link</button>
    </>
  );
}
