// homepage/homepage/content/docs/code-snippets/permissions-and-sharing/quickstart/NewBand.tsx
"use client";
// [!code --:2]
// @ts-expect-error Duplicate declaration
import { useAccount } from "jazz-tools/react";
// @ts-expect-error Duplicate declaration
import { JazzFestAccount } from "@/app/schema";
// [!code ++:3]
// @ts-expect-error Duplicate declaration
import { useAccount, useCoState } from "jazz-tools/react";
import { useState } from "react";
// @ts-expect-error Duplicate declaration
import { JazzFestAccount, Festival } from "@/app/schema";

// [!code ++:1]
export function NewBand({ id }: { id?: string }) {
  const me = useAccount(JazzFestAccount, {
    resolve: { root: { myFestival: true } },
  });
  const [name, setName] = useState("");

  // [!code ++:2]
  const festivalId =
    id ??
    (me.$isLoaded && me.root.$isLoaded
      ? me.root.myFestival.$jazz.id
      : undefined);
  const festival = useCoState(Festival, festivalId);

  const handleSave = () => {
    // [!code --:2]
    if (!me.$isLoaded) return;
    me.root.myFestival.$jazz.push({ name });
    // [!code ++:2]
    if (!festival.$isLoaded) return;
    festival.$jazz.push({ name });
    setName("");
  };

  return (
    <div>
      <input
        type="text"
        value={name}
        placeholder="Band name"
        onChange={(e) => setName(e.target.value)}
      />
      <button type="button" onClick={handleSave}>
        Add
      </button>
    </div>
  );
}

// homepage/homepage/content/docs/code-snippets/permissions-and-sharing/quickstart/NewBand.svelte
<script lang="ts">
  // [!code ++:2]
  import { AccountCoState, CoState } from "jazz-tools/svelte";
  import { JazzFestAccount, Festival } from "$lib/schema";

	const { id }: { id?: string } = $props();
  const me = new AccountCoState(JazzFestAccount, {
    resolve: { root: { myFestival: true } }
  });
  let name = $state("");

    // [!code ++:2]
  const festivalId = $derived(id ?? (me.current.$isLoaded && me.current.root.$isLoaded ? me.current.root.myFestival.$jazz.id : undefined));
	const festival = $derived(new CoState(Festival, festivalId));

  function handleSave() {
    // [!code --:2]
    if (!me.current.$isLoaded) return;
    me.current.root.myFestival.$jazz.push({ name });
    // [!code ++:2]
    if (!festival.current.$isLoaded) return;
    festival.current.$jazz.push({ name });
    name = "";
  }
</script>

<div>
  <input type="text" bind:value={name} placeholder="Band name" />
  <button type="button" onclick={handleSave}>Add</button>
</div>
