// homepage/homepage/content/docs/code-snippets/permissions-and-sharing/quickstart/+page.svelte
<script lang="ts">
  // @ts-expect-error Only in a real SK app
	import { page } from '$app/state';
	import Festival from '$lib/components/Festival.svelte';
	import NewBand from '$lib/components/NewBand.svelte';
	const { festivalId } = page.params;
</script>

<main>
  <h1>🎪 Festival {festivalId}</h1>
  <Festival id={festivalId} />
  <NewBand id={festivalId} />
</main>

// homepage/homepage/content/docs/code-snippets/permissions-and-sharing/quickstart/page.tsx
"use client";
import { use } from "react";
import { Festival } from "$lib/Festival";
import { NewBand } from "@/app/components/NewBand";

export default function FestivalPage(props: {
  params: Promise<{ festivalId: string }>;
}) {
  const { festivalId } = use(props.params);

  return (
    <main>
      <h1>🎪 Festival {festivalId}</h1>
      <Festival id={festivalId} />
      <NewBand id={festivalId} />
    </main>
  );
}
