// starters/svelte-passkey-auth/src/lib/components/Header.svelte
<script lang="ts">
  import { JazzAccount } from "$lib/schema";
  import { usePasskeyAuth } from "jazz-tools/svelte";
  import { AccountCoState } from "jazz-tools/svelte";

  let { appName } = $props();

  const { logOut } = new AccountCoState(JazzAccount);

  const { current, state } = $derived(
    usePasskeyAuth({
      appName,
    }),
  );

  const isAuthenticated = $derived(state === "signedIn");
</script>

<header>
  <nav class="flex justify-between items-center">
    {#if isAuthenticated}
      <span>You're logged in.</span>
    {:else}
      <span>Authenticate to share the data with another device.</span>
    {/if}

    {#if isAuthenticated}
      <button type="button" onclick={logOut} class="bg-stone-100 py-1.5 px-3 text-sm rounded-md">
        Log out
      </button>
    {:else}
      <div class="flex gap-2">
        <button
          type="button"
          class="bg-stone-100 py-1.5 px-3 text-sm rounded-md"
          onclick={() => current.signUp("")}
        >
          Sign up
        </button>
        <button
          type="button"
          class="bg-stone-100 py-1.5 px-3 text-sm rounded-md"
          onclick={() => current.logIn()}
        >
          Log in
        </button>
      </div>
    {/if}
  </nav>
</header>

// examples/vector-search/src/components/Header.tsx
import { useIsAuthenticated } from "jazz-tools/react";
import { AuthButton } from "./AuthButton";
import { Logo } from "./Logo";

export function Header({ isSeeding }: { isSeeding: boolean }) {
  const isAuthenticated = useIsAuthenticated();

  return (
    <header className="z-50 border-b border-zinc-200 bg-zinc-50 py-3 px-4 flex flex-col gap-2 md:flex-row md:items-center justify-between">
      <div className="flex flex-col gap-1">
        <a
          className="inline-block w-20 cursor-pointer"
          href="https://jazz.tools"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Logo />
        </a>

        <span className="text-xs text-zinc-500">
          Demo of local-first vector similarity search in Jazz.{" "}
          <a
            className="underline hover:no-underline"
            href="https://github.com/garden-co/jazz/tree/main/examples/vector-search"
            target="_blank"
            rel="noopener noreferrer"
          >
            Source →
          </a>
        </span>
      </div>

      <nav
        className={[
          "flex flex-col gap-2 md:flex-row md:items-center justify-between border-t border-zinc-200 pt-2 md:pt-0 md:border-t-0 transition-opacity",
          isSeeding && "opacity-0 pointer-events-none",
        ].join(" ")}
      >
        <div className="text-xs text-zinc-500">
          {isAuthenticated ? (
            <>You're logged in.</>
          ) : (
            <>Authenticate to share the data with another device.</>
          )}
        </div>

        <div className="flex gap-2">
          <AuthButton />
        </div>
      </nav>
    </header>
  );
}
